# All source files — SQL (part 2 of 2)

The four migrations are the **source of truth** for the database schema; `prisma/schema.prisma` is generated from them.

The `sql/` suites are verification, not application code: 49 constraint assertions, 20 RLS and refresh-token assertions, and 10 audit-evidence queries. Run them with `bash sql/run.sh` against a scratch database.

## Files in this document

| Path | Lines |
| --- | --- |
| `prisma/migrations/migration_lock.toml` | 3 |
| `prisma/migrations/20260801000000_core/migration.sql` | 228 |
| `prisma/migrations/20260801000001_cards/migration.sql` | 228 |
| `prisma/migrations/20260801000002_billing_audit_analytics/migration.sql` | 224 |
| `prisma/migrations/20260801000003_auth_hardening/migration.sql` | 234 |
| `sql/97_audit_evidence.sql` | 111 |
| `sql/98_auth_rls_tests.sql` | 268 |
| `sql/99_constraint_tests.sql` | 441 |
| `sql/run.sh` | 27 |

---

## `prisma/migrations/migration_lock.toml`

`````toml
# Please do not edit this file manually
# It should be added in your version-control system (e.g. Git)
provider = "postgresql"
`````

## `prisma/migrations/20260801000000_core/migration.sql`

`````sql
-- ============================================================
-- NFC Digital Identity Platform — Step 2, part 1
-- Enums, identity, access, profiles, slugs
-- Target: PostgreSQL 16
-- ============================================================

CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ---------- enums ----------
-- Enums over check constraints: they are self-documenting in \d output, which
-- matters when an auditor is reading the schema rather than the application.

CREATE TYPE data_region       AS ENUM ('eu', 'us', 'in');
CREATE TYPE account_status    AS ENUM ('pending', 'active', 'suspended', 'tombstoned');
CREATE TYPE platform_role     AS ENUM ('none', 'support', 'admin', 'super_admin');
CREATE TYPE org_status        AS ENUM ('active', 'suspended', 'closed');
CREATE TYPE org_role          AS ENUM ('employee', 'manager', 'hr', 'org_admin');
CREATE TYPE membership_status AS ENUM ('invited', 'active', 'removed');
CREATE TYPE profile_status    AS ENUM ('draft', 'active', 'suspended', 'deleted');
CREATE TYPE card_status       AS ENUM ('manufactured', 'provisioned', 'claimed', 'active', 'suspended', 'revoked');
CREATE TYPE serving_state     AS ENUM ('unclaimed', 'active', 'lapsed', 'suspended', 'revoked');
CREATE TYPE chip_profile      AS ENUM ('ntag213', 'ntag215', 'ntag216', 'ntag424_dna');
CREATE TYPE sub_status        AS ENUM ('trialing', 'active', 'past_due', 'canceled', 'unpaid');
CREATE TYPE transfer_reason   AS ENUM ('activation', 'sale', 'gift', 'lost_replacement', 'org_reassignment', 'admin_correction');
CREATE TYPE tap_channel       AS ENUM ('nfc', 'qr', 'direct');
CREATE TYPE actor_scope       AS ENUM ('system', 'account', 'organization', 'platform');

-- ---------- organizations ----------

CREATE TABLE organizations (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name           text        NOT NULL,
    billing_email  citext      NOT NULL,
    status         org_status   NOT NULL DEFAULT 'active',
    data_region    data_region  NOT NULL,
    created_at     timestamptz  NOT NULL DEFAULT now(),
    updated_at     timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT organizations_name_not_blank CHECK (length(btrim(name)) > 0)
);

-- ---------- accounts ----------
-- email is nullable ONLY so erasure can null it while keeping the row as a
-- tombstone; audit rows reference accounts by id and must never dangle (§10).

CREATE TABLE accounts (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    email             citext,
    email_verified_at timestamptz,
    password_hash     text,
    full_name         text,
    platform_role     platform_role  NOT NULL DEFAULT 'none',
    status            account_status NOT NULL DEFAULT 'pending',
    data_region       data_region    NOT NULL,
    created_at        timestamptz    NOT NULL DEFAULT now(),
    updated_at        timestamptz    NOT NULL DEFAULT now(),
    tombstoned_at     timestamptz,

    -- A live account must be identifiable; a tombstone must not be.
    CONSTRAINT accounts_live_has_email CHECK (
        (tombstoned_at IS NULL  AND email IS NOT NULL)
     OR (tombstoned_at IS NOT NULL AND email IS NULL
         AND password_hash IS NULL AND full_name IS NULL
         AND status = 'tombstoned')
    )
);

-- Email uniqueness applies to live accounts only, so tombstoning frees the address.
CREATE UNIQUE INDEX accounts_email_live_key
    ON accounts (email) WHERE tombstoned_at IS NULL;

CREATE INDEX accounts_platform_role_idx
    ON accounts (platform_role) WHERE platform_role <> 'none';

-- ---------- org memberships ----------
-- UNIQUE (account_id, org_id) is load-bearing: cards references it to prove a
-- holder belongs to the owning organisation (§6).

CREATE TABLE org_memberships (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id      uuid NOT NULL REFERENCES organizations (id) ON DELETE RESTRICT,
    account_id  uuid NOT NULL REFERENCES accounts (id)      ON DELETE RESTRICT,
    role        org_role          NOT NULL DEFAULT 'employee',
    status      membership_status NOT NULL DEFAULT 'invited',
    invited_by  uuid REFERENCES accounts (id) ON DELETE SET NULL,
    joined_at   timestamptz,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT org_memberships_account_org_key UNIQUE (account_id, org_id)
);

CREATE INDEX org_memberships_org_idx ON org_memberships (org_id, status);

-- ---------- sessions ----------
-- Server-side sessions, not JWTs, so revocation is immediate (§9).

CREATE TABLE sessions (
    id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    account_id         uuid NOT NULL REFERENCES accounts (id) ON DELETE CASCADE,
    family_id          uuid NOT NULL,
    refresh_token_hash bytea NOT NULL,
    device_label       text,
    device_class       text,
    ip_country         char(2),
    created_at         timestamptz NOT NULL DEFAULT now(),
    last_seen_at       timestamptz NOT NULL DEFAULT now(),
    expires_at         timestamptz NOT NULL,
    revoked_at         timestamptz,
    revoked_reason     text,
    CONSTRAINT sessions_refresh_hash_key UNIQUE (refresh_token_hash)
);

CREATE INDEX sessions_account_live_idx
    ON sessions (account_id, last_seen_at DESC) WHERE revoked_at IS NULL;
CREATE INDEX sessions_family_idx ON sessions (family_id);

-- ---------- otp codes ----------

CREATE TABLE otp_codes (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    account_id  uuid NOT NULL REFERENCES accounts (id) ON DELETE CASCADE,
    purpose     text  NOT NULL,
    code_hash   bytea NOT NULL,
    attempts    int   NOT NULL DEFAULT 0,
    expires_at  timestamptz NOT NULL,
    consumed_at timestamptz,
    created_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT otp_attempts_bounded CHECK (attempts >= 0 AND attempts <= 10)
);

CREATE INDEX otp_codes_account_idx
    ON otp_codes (account_id, purpose) WHERE consumed_at IS NULL;

-- ---------- profiles ----------
-- Owned by exactly one of account or organization (§2.6). The two partial
-- unique indexes below are what let cards prove "profile belongs to holder"
-- and "profile belongs to owning org" as plain foreign keys.

CREATE TABLE profiles (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_account_id  uuid REFERENCES accounts (id)      ON DELETE RESTRICT,
    owner_org_id      uuid REFERENCES organizations (id) ON DELETE RESTRICT,
    current_slug      citext NOT NULL,
    display_name      text   NOT NULL,
    headline          text,
    bio               text,
    links             jsonb  NOT NULL DEFAULT '{}'::jsonb,
    theme             text   NOT NULL DEFAULT 'default',
    template          text   NOT NULL DEFAULT 'standard',
    avatar_key        text,
    resume_key        text,
    status            profile_status NOT NULL DEFAULT 'draft',
    published_at      timestamptz,
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT profiles_single_owner CHECK (
        num_nonnulls(owner_account_id, owner_org_id) = 1
    ),
    CONSTRAINT profiles_links_is_object CHECK (jsonb_typeof(links) = 'object')
);

-- Referenced by the composite foreign keys on cards. These MUST NOT be partial:
-- Postgres will not let a foreign key reference a partial unique index. They are
-- redundant given id is already the primary key, which is precisely why they are
-- free to add -- their only job is to make the ownership invariants expressible
-- as declarative foreign keys instead of triggers.
ALTER TABLE profiles ADD CONSTRAINT profiles_id_owner_account_key
    UNIQUE (id, owner_account_id);
ALTER TABLE profiles ADD CONSTRAINT profiles_id_owner_org_key
    UNIQUE (id, owner_org_id);

CREATE INDEX profiles_owner_account_idx ON profiles (owner_account_id) WHERE owner_account_id IS NOT NULL;
CREATE INDEX profiles_owner_org_idx     ON profiles (owner_org_id)     WHERE owner_org_id IS NOT NULL;

-- ---------- slugs ----------
-- ONE table owns the entire slug namespace: current slugs, retired slugs, and
-- platform reservations all collide on the same primary key. A retired slug can
-- never be reissued to a different profile, so every link ever shared keeps
-- resolving to the same identity forever. Reservations are rows with no profile,
-- which blocks impersonation without needing a trigger or a subquery.

CREATE TYPE slug_kind AS ENUM ('current', 'retired', 'reserved');

CREATE TABLE slugs (
    slug        citext PRIMARY KEY,
    kind        slug_kind NOT NULL,
    profile_id  uuid REFERENCES profiles (id) ON DELETE RESTRICT,
    reason      text,
    created_at  timestamptz NOT NULL DEFAULT now(),
    retired_at  timestamptz,

    CONSTRAINT slugs_profile_presence CHECK (
        (kind = 'reserved' AND profile_id IS NULL)
     OR (kind <> 'reserved' AND profile_id IS NOT NULL)
    ),
    CONSTRAINT slugs_retired_timestamp CHECK (
        (kind = 'retired' AND retired_at IS NOT NULL)
     OR (kind <> 'retired' AND retired_at IS NULL)
    ),
    -- Reservations may be short — claiming 't' and 'u' is the whole point.
    -- User-facing slugs need at least 3 characters.
    CONSTRAINT slugs_shape CHECK (slug ~ '^[a-z0-9]([a-z0-9-]{0,38}[a-z0-9])?$'),
    CONSTRAINT slugs_user_min_length CHECK (
        kind = 'reserved' OR length(slug) >= 3
    )
);

-- Exactly one current slug per profile.
CREATE UNIQUE INDEX slugs_one_current_per_profile
    ON slugs (profile_id) WHERE kind = 'current';

CREATE INDEX slugs_profile_idx ON slugs (profile_id) WHERE profile_id IS NOT NULL;

-- profiles.current_slug must name a real slug. Deferred so a profile and its
-- first slug can be inserted in either order inside one transaction.
ALTER TABLE profiles
    ADD CONSTRAINT profiles_current_slug_fk
    FOREIGN KEY (current_slug) REFERENCES slugs (slug)
    DEFERRABLE INITIALLY DEFERRED;

INSERT INTO slugs (slug, kind, reason) VALUES
    ('admin','reserved','platform'),      ('api','reserved','platform'),
    ('t','reserved','resolver'),          ('u','reserved','profile-namespace'),
    ('login','reserved','platform'),      ('signup','reserved','platform'),
    ('support','reserved','impersonation'),('billing','reserved','impersonation'),
    ('security','reserved','impersonation'),('help','reserved','platform'),
    ('www','reserved','platform'),        ('settings','reserved','platform');
`````

## `prisma/migrations/20260801000001_cards/migration.sql`

`````sql
-- ============================================================
-- Step 2, part 2 — cards and the ownership invariants
-- ============================================================

-- ---------- card batches ----------

CREATE TABLE card_batches (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id        uuid REFERENCES organizations (id) ON DELETE RESTRICT,
    chip          chip_profile NOT NULL,
    quantity      int NOT NULL,
    manufacturer  text,
    created_at    timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT card_batches_quantity_positive CHECK (quantity > 0)
);

-- ---------- cards ----------
-- The token is NEVER stored in plaintext. The resolver hashes the incoming
-- token and looks up the hash, so a database disclosure does not hand an
-- attacker a catalogue of live tokens mapped to identities. token_prefix is
-- kept unhashed purely so support can find "the card ending in ...".
--
-- Three edges (§0.1): owner = title, holder = custody, profile = what it serves.

CREATE TABLE cards (
    id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    token_hash         bytea NOT NULL,
    token_prefix       char(6) NOT NULL,
    batch_id           uuid REFERENCES card_batches (id) ON DELETE RESTRICT,
    chip               chip_profile NOT NULL,

    owner_account_id   uuid REFERENCES accounts (id)      ON DELETE RESTRICT,
    owner_org_id       uuid REFERENCES organizations (id) ON DELETE RESTRICT,
    holder_account_id  uuid REFERENCES accounts (id)      ON DELETE RESTRICT,
    profile_id         uuid REFERENCES profiles (id)      ON DELETE RESTRICT,

    -- Denormalised so the resolver answers from one row with no join (§5.1).
    -- Kept consistent by the write path; reconciled on a schedule (§2.2).
    serving_slug       citext,
    serving_state      serving_state NOT NULL DEFAULT 'unclaimed',

    status             card_status NOT NULL DEFAULT 'manufactured',
    claim_code_hash    text,
    claim_attempts     int NOT NULL DEFAULT 0,
    claim_locked_until timestamptz,

    dna_key_ref        text,
    dna_counter        bigint,

    -- Discriminator for the personal-ownership foreign key below. NULL whenever
    -- the card is NOT personally owned, which is what makes MATCH SIMPLE stand
    -- the constraint down for organisation-owned cards. Generated, so it cannot
    -- drift from owner_account_id.
    personal_holder_id uuid GENERATED ALWAYS AS (
        CASE WHEN owner_account_id IS NOT NULL THEN holder_account_id END
    ) STORED,

    locked_at          timestamptz,
    claimed_at         timestamptz,
    activated_at       timestamptz,
    revoked_at         timestamptz,
    revoked_reason     text,
    created_at         timestamptz NOT NULL DEFAULT now(),
    updated_at         timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT cards_token_hash_key UNIQUE (token_hash),

    -- At most one owner, and an owned card must have exactly one.
    CONSTRAINT cards_single_owner CHECK (
        num_nonnulls(owner_account_id, owner_org_id) <= 1
    ),

    -- An active card must be fully bound and must have been locked at encoding.
    CONSTRAINT cards_active_is_bound CHECK (
        status <> 'active' OR (
            num_nonnulls(owner_account_id, owner_org_id) = 1
            AND holder_account_id IS NOT NULL
            AND profile_id        IS NOT NULL
            AND serving_slug      IS NOT NULL
            AND locked_at         IS NOT NULL
        )
    ),

    -- Revoked is terminal and must record why.
    CONSTRAINT cards_revoked_has_reason CHECK (
        status <> 'revoked' OR (revoked_at IS NOT NULL AND revoked_reason IS NOT NULL)
    ),

    -- Only a revoked card may carry serving_state 'revoked', and vice versa.
    CONSTRAINT cards_revoked_state_agrees CHECK (
        (status = 'revoked') = (serving_state = 'revoked')
    ),

    -- DNA cards must reference a key; basic chips must not pretend to.
    CONSTRAINT cards_dna_key_present CHECK (
        (chip = 'ntag424_dna') = (dna_key_ref IS NOT NULL)
    ),

    CONSTRAINT cards_claim_attempts_bounded CHECK (claim_attempts >= 0)
);

-- ============================================================
-- The ownership invariants, enforced as plain foreign keys.
--
-- All three use Postgres's default MATCH SIMPLE: a composite FK containing a
-- NULL column is NOT enforced. So each key activates only for the ownership
-- shape it governs, with no triggers and no application logic.
--
-- CRITICAL SUBTLETY: MATCH SIMPLE only stands down when a column *inside the
-- key* is NULL. The discriminator therefore has to BE a key column. An earlier
-- draft used (profile_id, holder_account_id) for the personal key, reasoning
-- that owner_account_id IS NULL would disable it for org cards -- but
-- owner_account_id is not in that key, and both of its columns are populated on
-- an org card, so the constraint fired and made org cards impossible to insert.
-- Hence personal_holder_id: generated, NULL for org-owned cards, in the key.
--
--   personal card -> owner_org_id IS NULL       -> org keys stand down
--   org card      -> personal_holder_id IS NULL -> personal key stands down
-- ============================================================

-- 1. Personal card: the profile must belong to the holder.
ALTER TABLE cards
    ADD CONSTRAINT cards_personal_profile_belongs_to_holder
    FOREIGN KEY (profile_id, personal_holder_id)
    REFERENCES profiles (id, owner_account_id);

-- 2. Org card: the profile must belong to the owning organisation.
ALTER TABLE cards
    ADD CONSTRAINT cards_org_profile_belongs_to_org
    FOREIGN KEY (profile_id, owner_org_id)
    REFERENCES profiles (id, owner_org_id);

-- 3. Org card: the holder must be a member of the owning organisation.
ALTER TABLE cards
    ADD CONSTRAINT cards_org_holder_is_member
    FOREIGN KEY (holder_account_id, owner_org_id)
    REFERENCES org_memberships (account_id, org_id);

-- ---------- resolver indexes ----------
-- The only index the hot path uses. Partial, because the resolver never asks
-- about cards that cannot serve, which keeps it small enough to stay cached.

CREATE INDEX cards_resolver_idx
    ON cards (token_hash) INCLUDE (serving_state, serving_slug);

CREATE INDEX cards_token_prefix_idx  ON cards (token_prefix);
CREATE INDEX cards_holder_idx        ON cards (holder_account_id) WHERE holder_account_id IS NOT NULL;
CREATE INDEX cards_owner_org_idx     ON cards (owner_org_id)      WHERE owner_org_id IS NOT NULL;
CREATE INDEX cards_owner_account_idx ON cards (owner_account_id)  WHERE owner_account_id IS NOT NULL;
CREATE INDEX cards_profile_idx       ON cards (profile_id)        WHERE profile_id IS NOT NULL;

-- Drift reconciliation sweeps by state; keep it cheap.
CREATE INDEX cards_serving_state_idx ON cards (serving_state, updated_at);

-- ---------- ownership transfers (append-only) ----------
-- The record of TITLE. Every change of owner, forever. Activation is the first
-- row, with a null "from".

CREATE TABLE ownership_transfers (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    card_id           uuid NOT NULL REFERENCES cards (id) ON DELETE RESTRICT,
    from_account_id   uuid REFERENCES accounts (id)      ON DELETE RESTRICT,
    from_org_id       uuid REFERENCES organizations (id) ON DELETE RESTRICT,
    to_account_id     uuid REFERENCES accounts (id)      ON DELETE RESTRICT,
    to_org_id         uuid REFERENCES organizations (id) ON DELETE RESTRICT,
    reason            transfer_reason NOT NULL,
    requested_by      uuid REFERENCES accounts (id) ON DELETE RESTRICT,
    approved_by       uuid REFERENCES accounts (id) ON DELETE RESTRICT,
    approved_at       timestamptz NOT NULL DEFAULT now(),
    correlation_id    uuid,
    created_at        timestamptz NOT NULL DEFAULT now(),

    -- A transfer must land somewhere, on exactly one kind of owner.
    CONSTRAINT transfers_single_destination CHECK (
        num_nonnulls(to_account_id, to_org_id) = 1
    ),
    -- Origin is either absent (activation) or exactly one kind.
    CONSTRAINT transfers_origin_shape CHECK (
        (reason = 'activation' AND num_nonnulls(from_account_id, from_org_id) = 0)
     OR (reason <> 'activation' AND num_nonnulls(from_account_id, from_org_id) = 1)
    ),
    -- Only an admin correction may lack a named approver.
    CONSTRAINT transfers_approved CHECK (
        approved_by IS NOT NULL OR reason = 'activation'
    )
);

CREATE INDEX transfers_card_idx ON ownership_transfers (card_id, approved_at DESC);

-- ---------- card assignments (append-only) ----------
-- Holder changes for org cards. NOT transfers: title does not move, so these
-- deliberately do not pollute the ownership record.

CREATE TABLE card_assignments (
    id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    card_id          uuid NOT NULL REFERENCES cards (id) ON DELETE RESTRICT,
    from_account_id  uuid REFERENCES accounts (id) ON DELETE RESTRICT,
    to_account_id    uuid REFERENCES accounts (id) ON DELETE RESTRICT,
    assigned_by      uuid NOT NULL REFERENCES accounts (id) ON DELETE RESTRICT,
    correlation_id   uuid,
    created_at       timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT assignments_changes_something CHECK (
        from_account_id IS DISTINCT FROM to_account_id
    )
);

CREATE INDEX assignments_card_idx ON card_assignments (card_id, created_at DESC);

-- ---------- encodings (append-only) ----------
-- The immutable proof that a chip was locked, by whom, on which station (§7.3).
-- This replaces a mutable chip_locked boolean: a flag can be flipped by a bug,
-- an append-only row cannot be un-written.

CREATE TABLE card_encodings (
    id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    card_id            uuid NOT NULL REFERENCES cards (id) ON DELETE RESTRICT,
    encoder_account_id uuid NOT NULL REFERENCES accounts (id) ON DELETE RESTRICT,
    station_id         text NOT NULL,
    chip               chip_profile NOT NULL,
    locked             boolean NOT NULL,
    verify_read_ok     boolean NOT NULL,
    occurred_at        timestamptz NOT NULL DEFAULT now(),

    -- A card may only ship if the lock was applied AND read back successfully.
    CONSTRAINT encodings_lock_verified CHECK (NOT locked OR verify_read_ok)
);

CREATE INDEX encodings_card_idx ON card_encodings (card_id, occurred_at DESC);
`````

## `prisma/migrations/20260801000002_billing_audit_analytics/migration.sql`

`````sql
-- ============================================================
-- Step 2, part 3 — billing, audit, analytics
-- ============================================================

-- ---------- subscriptions ----------
-- Same dual-owner idiom as cards, deliberately (§2.5): one pattern an auditor
-- learns once and can then verify everywhere.

CREATE TABLE subscriptions (
    id                     uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_account_id       uuid REFERENCES accounts (id)      ON DELETE RESTRICT,
    owner_org_id           uuid REFERENCES organizations (id) ON DELETE RESTRICT,
    plan                   text NOT NULL,
    status                 sub_status NOT NULL,
    seats                  int NOT NULL DEFAULT 1,
    stripe_customer_id     text,
    stripe_subscription_id text,
    current_period_end     timestamptz,
    cancel_at              timestamptz,
    created_at             timestamptz NOT NULL DEFAULT now(),
    updated_at             timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT subscriptions_single_owner CHECK (
        num_nonnulls(owner_account_id, owner_org_id) = 1
    ),
    CONSTRAINT subscriptions_seats_positive CHECK (seats > 0),
    -- A personal plan cannot have seats; an org plan is the only multi-seat shape.
    CONSTRAINT subscriptions_personal_single_seat CHECK (
        owner_account_id IS NULL OR seats = 1
    ),
    CONSTRAINT subscriptions_stripe_sub_key UNIQUE (stripe_subscription_id)
);

CREATE UNIQUE INDEX subscriptions_one_live_per_account
    ON subscriptions (owner_account_id)
    WHERE owner_account_id IS NOT NULL AND status IN ('trialing','active','past_due');

CREATE UNIQUE INDEX subscriptions_one_live_per_org
    ON subscriptions (owner_org_id)
    WHERE owner_org_id IS NOT NULL AND status IN ('trialing','active','past_due');

-- ---------- stripe webhook idempotency ----------
-- Stripe redelivers. Without this, a redelivered invoice event double-applies.

CREATE TABLE stripe_events (
    stripe_event_id text PRIMARY KEY,
    type            text NOT NULL,
    payload         jsonb NOT NULL,
    received_at     timestamptz NOT NULL DEFAULT now(),
    processed_at    timestamptz,
    error           text
);

CREATE INDEX stripe_events_unprocessed_idx
    ON stripe_events (received_at) WHERE processed_at IS NULL;

-- ---------- generic API idempotency ----------

CREATE TABLE idempotency_keys (
    key           text PRIMARY KEY,
    account_id    uuid REFERENCES accounts (id) ON DELETE CASCADE,
    endpoint      text NOT NULL,
    request_hash  bytea NOT NULL,
    response_code int,
    response_body jsonb,
    created_at    timestamptz NOT NULL DEFAULT now(),
    completed_at  timestamptz
);

CREATE INDEX idempotency_keys_created_idx ON idempotency_keys (created_at);

-- ============================================================
-- Audit log — partitioned monthly, append-only.
--
-- Actors are referenced by opaque id ONLY. No email, no name. That is what
-- lets erasure tombstone an account (§10) while the audit history survives
-- intact: the id remains, and it no longer resolves to a person.
-- ============================================================

CREATE TABLE audit_log (
    id             uuid NOT NULL DEFAULT gen_random_uuid(),
    occurred_at    timestamptz NOT NULL DEFAULT now(),
    actor_scope    actor_scope NOT NULL,
    actor_account_id uuid,
    actor_org_id     uuid,
    action         text NOT NULL,
    subject_type   text NOT NULL,
    subject_id     uuid,
    before         jsonb,
    after          jsonb,
    correlation_id uuid,
    ip_country     char(2),
    PRIMARY KEY (id, occurred_at),

    -- A system action has no actor; every other scope must name one.
    CONSTRAINT audit_actor_shape CHECK (
        (actor_scope = 'system' AND actor_account_id IS NULL)
     OR (actor_scope <> 'system' AND actor_account_id IS NOT NULL)
    )
) PARTITION BY RANGE (occurred_at);

CREATE INDEX audit_log_subject_idx ON audit_log (subject_type, subject_id, occurred_at DESC);
CREATE INDEX audit_log_actor_idx   ON audit_log (actor_account_id, occurred_at DESC);

-- NOTE: audit_log deliberately carries NO foreign key to accounts. An FK would
-- force ON DELETE behaviour on a table that must never lose rows, and would let
-- account deletion cascade into the audit trail. Referential integrity here is
-- one-directional by design: accounts are tombstoned, never deleted (§10).

CREATE TABLE audit_log_2026_08 PARTITION OF audit_log
    FOR VALUES FROM ('2026-08-01') TO ('2026-09-01');
CREATE TABLE audit_log_2026_09 PARTITION OF audit_log
    FOR VALUES FROM ('2026-09-01') TO ('2026-10-01');
CREATE TABLE audit_log_default PARTITION OF audit_log DEFAULT;

-- ============================================================
-- tap_events — ~100M rows/month, ~1.2B/year (§1).
--
-- Partitioned by REGION first, then by month. Region-first is the decision that
-- keeps data residency open: an EU-only deployment becomes a partition move
-- rather than a 1.2-billion-row rewrite. Carrying the dimension unused costs
-- almost nothing; adding it later is one of the most expensive migrations in
-- this class of system.
--
-- Contains data about VISITORS, who never agreed to anything. Therefore: no raw
-- IP, device class not fingerprint, retention by partition drop (§8).
-- ============================================================

CREATE TABLE tap_events (
    id            bigint GENERATED ALWAYS AS IDENTITY,
    occurred_at   timestamptz NOT NULL DEFAULT now(),
    region        data_region NOT NULL,
    card_id       uuid,
    profile_id    uuid NOT NULL,
    channel       tap_channel NOT NULL DEFAULT 'nfc',
    country       char(2),
    device_class  text,
    referrer_host text,
    is_bot        boolean NOT NULL DEFAULT false,
    PRIMARY KEY (id, region, occurred_at)
) PARTITION BY LIST (region);

-- No foreign keys. At 800 writes/sec on the ingest path an FK check per row is
-- pure overhead, and a dangling card_id after a hard delete is acceptable in an
-- analytics table where cards are RESTRICT-protected anyway.

CREATE TABLE tap_events_eu PARTITION OF tap_events
    FOR VALUES IN ('eu') PARTITION BY RANGE (occurred_at);
CREATE TABLE tap_events_us PARTITION OF tap_events
    FOR VALUES IN ('us') PARTITION BY RANGE (occurred_at);
CREATE TABLE tap_events_in PARTITION OF tap_events
    FOR VALUES IN ('in') PARTITION BY RANGE (occurred_at);

CREATE TABLE tap_events_eu_2026_08 PARTITION OF tap_events_eu
    FOR VALUES FROM ('2026-08-01') TO ('2026-09-01');
CREATE TABLE tap_events_eu_2026_09 PARTITION OF tap_events_eu
    FOR VALUES FROM ('2026-09-01') TO ('2026-10-01');
CREATE TABLE tap_events_us_2026_08 PARTITION OF tap_events_us
    FOR VALUES FROM ('2026-08-01') TO ('2026-09-01');
CREATE TABLE tap_events_us_2026_09 PARTITION OF tap_events_us
    FOR VALUES FROM ('2026-09-01') TO ('2026-10-01');
CREATE TABLE tap_events_in_2026_08 PARTITION OF tap_events_in
    FOR VALUES FROM ('2026-08-01') TO ('2026-09-01');
CREATE TABLE tap_events_in_2026_09 PARTITION OF tap_events_in
    FOR VALUES FROM ('2026-09-01') TO ('2026-10-01');

CREATE INDEX tap_events_profile_idx ON tap_events (profile_id, occurred_at DESC);
CREATE INDEX tap_events_card_idx    ON tap_events (card_id, occurred_at DESC);

-- ---------- rollups ----------
-- The dashboard reads ONLY these. It must never touch tap_events, and these
-- outlive the raw partitions so analytics survive retention drops (§8).

CREATE TABLE tap_daily (
    profile_id   uuid NOT NULL,
    day          date NOT NULL,
    region       data_region NOT NULL,
    taps         bigint NOT NULL DEFAULT 0,
    nfc_taps     bigint NOT NULL DEFAULT 0,
    qr_taps      bigint NOT NULL DEFAULT 0,
    bot_taps     bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (profile_id, day, region)
);

CREATE TABLE tap_daily_country (
    profile_id uuid NOT NULL,
    day        date NOT NULL,
    country    char(2) NOT NULL,
    taps       bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (profile_id, day, country)
);

CREATE INDEX tap_daily_day_idx ON tap_daily (day);

-- ============================================================
-- Append-only enforcement (§10).
--
-- A database grant, not a convention. The application role physically cannot
-- rewrite history, so "immutable audit trail" is a property an auditor can
-- verify with \dp rather than a claim about code review discipline.
-- ============================================================

-- Roles are cluster-scoped, so creation must be idempotent for repeatable runs.
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_rw') THEN
        CREATE ROLE app_rw NOLOGIN;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_resolver') THEN
        CREATE ROLE app_resolver NOLOGIN;
    END IF;
END $$;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app_rw;

REVOKE UPDATE, DELETE ON ownership_transfers FROM app_rw;
REVOKE UPDATE, DELETE ON card_assignments    FROM app_rw;
REVOKE UPDATE, DELETE ON card_encodings      FROM app_rw;
REVOKE UPDATE, DELETE ON audit_log           FROM app_rw;
REVOKE DELETE           ON slugs             FROM app_rw;
REVOKE DELETE           ON accounts          FROM app_rw;

-- The resolver reads one table and nothing else. Least privilege at the
-- database level means a resolver compromise cannot read profiles or accounts.
GRANT SELECT (token_hash, serving_state, serving_slug) ON cards TO app_resolver;
`````

## `prisma/migrations/20260801000003_auth_hardening/migration.sql`

`````sql
-- ============================================================
-- Step 3, migration 04 — auth hardening
--
--   a) refresh token rotation with reuse detection
--   b) row-level security on tenant-scoped tables
--
-- (a) is a correction: Step 2's sessions table stored only the CURRENT refresh
-- token hash, which makes a replayed old token indistinguishable from a random
-- invalid one. Reuse detection requires retaining used tokens.
-- ============================================================

-- ------------------------------------------------------------
-- (a) refresh token rotation
-- ------------------------------------------------------------

-- The session is now the device login. Its id IS the token family, so the
-- separate family_id column is redundant.
ALTER TABLE sessions DROP CONSTRAINT IF EXISTS sessions_refresh_hash_key;
ALTER TABLE sessions DROP COLUMN IF EXISTS refresh_token_hash;
ALTER TABLE sessions DROP COLUMN IF EXISTS family_id;

-- One row per refresh token ever issued for a session. Rotation marks the old
-- token used and points it at its successor; presenting a used token is proof
-- of theft, because a well-behaved client discards a token the moment it
-- exchanges it.
CREATE TABLE refresh_tokens (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id   uuid  NOT NULL REFERENCES sessions (id) ON DELETE CASCADE,
    token_hash   bytea NOT NULL,
    issued_at    timestamptz NOT NULL DEFAULT now(),
    expires_at   timestamptz NOT NULL,
    used_at      timestamptz,
    replaced_by  uuid REFERENCES refresh_tokens (id) ON DELETE SET NULL,

    CONSTRAINT refresh_tokens_hash_key UNIQUE (token_hash),

    -- A used token must name its successor. This is what makes reuse detection
    -- possible rather than merely intended.
    CONSTRAINT refresh_tokens_used_has_successor CHECK (
        (used_at IS NULL AND replaced_by IS NULL)
     OR (used_at IS NOT NULL AND replaced_by IS NOT NULL)
    ),
    CONSTRAINT refresh_tokens_expiry_after_issue CHECK (expires_at > issued_at)
);

CREATE INDEX refresh_tokens_session_idx  ON refresh_tokens (session_id, issued_at DESC);
CREATE INDEX refresh_tokens_live_idx     ON refresh_tokens (expires_at) WHERE used_at IS NULL;

COMMENT ON TABLE refresh_tokens IS
  'One row per issued refresh token. A hit with used_at NOT NULL is a replay: revoke the entire session and raise a security event.';

-- Security events are audit rows, not a separate table -- one immutable log.
COMMENT ON COLUMN sessions.revoked_reason IS
  'e.g. user_signout, refresh_reuse_detected, admin_revoked, password_changed.';

-- ------------------------------------------------------------
-- (b) row-level security
--
-- Deferred in Step 2 §8, adopted here. The argument is not that it stops a
-- compromised application server -- it does not, since the app supplies the
-- identity. The argument is that tenant scoping becomes ONE predicate the
-- database enforces on every query, instead of a WHERE clause every developer
-- must remember on every query forever. It converts a whole class of IDOR bug
-- from "possible" to "impossible without also removing a policy".
--
-- Fails closed: with no app.account_id set, the predicates compare against
-- NULL, which is never true, so queries return zero rows rather than
-- everything.
-- ------------------------------------------------------------

-- Pinned search_path: a SECURITY DEFINER function without one is a privilege
-- escalation vector, and is the first thing an assessor greps for.
CREATE OR REPLACE FUNCTION app_current_account() RETURNS uuid
    LANGUAGE sql STABLE
    SET search_path = pg_catalog, public
AS $$
    SELECT nullif(current_setting('app.account_id', true), '')::uuid
$$;

-- SECURITY DEFINER so it can read org_memberships without RLS recursion:
-- a policy that queried the table directly would re-enter that table's own
-- policy. STABLE so it evaluates once per query, not once per row.
CREATE OR REPLACE FUNCTION app_current_org_ids() RETURNS uuid[]
    LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path = pg_catalog, public
AS $$
    SELECT coalesce(array_agg(org_id), '{}'::uuid[])
      FROM org_memberships
     WHERE account_id = app_current_account()
       AND status = 'active'
$$;

REVOKE ALL ON FUNCTION app_current_org_ids() FROM PUBLIC;

-- The admin surface is a separate database role, so "admins see everything" is
-- a visible policy an assessor can read rather than an application if-statement.
-- Four application roles, each with the narrowest grant that lets it work.
-- Least privilege is expressed as roles + policies, so a compromise of any one
-- service is bounded by something an assessor can read.
DO $$
DECLARE r text;
BEGIN
    FOREACH r IN ARRAY ARRAY['app_admin','app_renderer','app_auth'] LOOP
        IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r) THEN
            EXECUTE format('CREATE ROLE %I NOLOGIN', r);
        END IF;
    END LOOP;
END $$;

-- The public renderer reads published profile content and nothing else.
GRANT SELECT ON profiles, slugs TO app_renderer;

-- The authenticator owns credential verification and token rotation only.
GRANT SELECT, INSERT, UPDATE ON sessions TO app_auth;
GRANT SELECT ON accounts TO app_auth;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app_admin;
REVOKE UPDATE, DELETE ON ownership_transfers, card_assignments,
                         card_encodings, audit_log FROM app_admin;

GRANT SELECT, INSERT, UPDATE, DELETE ON refresh_tokens TO app_rw, app_admin;
GRANT EXECUTE ON FUNCTION app_current_account(), app_current_org_ids()
    TO app_rw, app_admin;

-- ---------- profiles ----------

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY profiles_tenant ON profiles
    FOR ALL TO app_rw
    USING (
        owner_account_id = app_current_account()
     OR owner_org_id     = ANY (app_current_org_ids())
    )
    WITH CHECK (
        owner_account_id = app_current_account()
     OR owner_org_id     = ANY (app_current_org_ids())
    );

CREATE POLICY profiles_admin ON profiles FOR ALL TO app_admin USING (true) WITH CHECK (true);

-- The public profile renderer needs to read any published profile by slug, and
-- must never see drafts or suspended profiles. That is a policy, not a filter
-- the renderer is trusted to remember.
CREATE POLICY profiles_public_read ON profiles
    FOR SELECT TO app_renderer
    USING (status = 'active');

-- ---------- cards ----------

ALTER TABLE cards ENABLE ROW LEVEL SECURITY;

CREATE POLICY cards_tenant ON cards
    FOR ALL TO app_rw
    USING (
        holder_account_id = app_current_account()
     OR owner_account_id  = app_current_account()
     OR owner_org_id      = ANY (app_current_org_ids())
    )
    WITH CHECK (
        holder_account_id = app_current_account()
     OR owner_account_id  = app_current_account()
     OR owner_org_id      = ANY (app_current_org_ids())
    );

CREATE POLICY cards_admin ON cards FOR ALL TO app_admin USING (true) WITH CHECK (true);

-- The resolver must resolve ANY token -- it has no user context. Its blast
-- radius is bounded by column-level grants instead (three columns, §4.7).
CREATE POLICY cards_resolver ON cards FOR SELECT TO app_resolver USING (true);

-- ---------- subscriptions ----------

ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;

CREATE POLICY subscriptions_tenant ON subscriptions
    FOR ALL TO app_rw
    USING (
        owner_account_id = app_current_account()
     OR owner_org_id     = ANY (app_current_org_ids())
    )
    WITH CHECK (
        owner_account_id = app_current_account()
     OR owner_org_id     = ANY (app_current_org_ids())
    );

CREATE POLICY subscriptions_admin ON subscriptions FOR ALL TO app_admin USING (true) WITH CHECK (true);

-- ---------- org memberships ----------
-- Who works where is personal data. Visible to the member themselves and to
-- fellow members of the same organisation.

ALTER TABLE org_memberships ENABLE ROW LEVEL SECURITY;

CREATE POLICY org_memberships_tenant ON org_memberships
    FOR ALL TO app_rw
    USING (
        account_id = app_current_account()
     OR org_id     = ANY (app_current_org_ids())
    )
    WITH CHECK (
        org_id = ANY (app_current_org_ids())
    );

CREATE POLICY org_memberships_admin ON org_memberships FOR ALL TO app_admin USING (true) WITH CHECK (true);

-- ---------- sessions and refresh tokens ----------
-- A session listing must never leak another account's devices.

ALTER TABLE sessions       ENABLE ROW LEVEL SECURITY;
ALTER TABLE refresh_tokens ENABLE ROW LEVEL SECURITY;

CREATE POLICY sessions_own ON sessions
    FOR ALL TO app_rw
    USING (account_id = app_current_account())
    WITH CHECK (account_id = app_current_account());

CREATE POLICY sessions_admin ON sessions FOR ALL TO app_admin USING (true) WITH CHECK (true);

-- Refresh token lookup happens BEFORE an identity exists -- the token is what
-- establishes it. So the authenticator uses its own role, and app_rw sees only
-- its own rows for the "sign out everywhere" listing.
CREATE POLICY refresh_tokens_own ON refresh_tokens
    FOR ALL TO app_rw
    USING (session_id IN (SELECT id FROM sessions WHERE account_id = app_current_account()))
    WITH CHECK (session_id IN (SELECT id FROM sessions WHERE account_id = app_current_account()));

CREATE POLICY refresh_tokens_authenticator ON refresh_tokens
    FOR ALL TO app_auth USING (true) WITH CHECK (true);

CREATE POLICY sessions_authenticator ON sessions
    FOR ALL TO app_auth USING (true) WITH CHECK (true);

CREATE POLICY refresh_tokens_admin ON refresh_tokens FOR ALL TO app_admin USING (true) WITH CHECK (true);
`````

## `sql/97_audit_evidence.sql`

`````sql
-- ============================================================
-- Step 3 — audit evidence pack
--
-- An assessor does not want a document claiming controls exist. They want to
-- run something. Each query below answers one question they will ask, and each
-- is designed so the WRONG answer is visibly wrong rather than absent.
--
--   psql -d <db> -f 97_audit_evidence.sql
-- ============================================================

\pset pager off
\pset border 2

\echo '\n### E1. Which tables are append-only, and is it enforced by grant?\n'
-- Expect exactly INSERT, SELECT on the four immutable tables. Any UPDATE or
-- DELETE here is a finding.
SELECT c.relname AS table_name,
       string_agg(DISTINCT a.privilege_type, ', ' ORDER BY a.privilege_type) AS app_rw_privileges
  FROM pg_class c
  CROSS JOIN LATERAL aclexplode(c.relacl) a
  JOIN pg_roles r ON r.oid = a.grantee
 WHERE r.rolname = 'app_rw'
   AND c.relname IN ('audit_log','ownership_transfers','card_assignments','card_encodings')
 GROUP BY c.relname
 ORDER BY c.relname;

\echo '\n### E2. Which tables enforce row-level security, and under which policies?\n'
SELECT c.relname AS table_name,
       c.relrowsecurity AS rls_enabled,
       count(p.polname) AS policies,
       string_agg(p.polname, ', ' ORDER BY p.polname) AS policy_names
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace
  LEFT JOIN pg_policy p ON p.polrelid = c.oid
 WHERE n.nspname = 'public' AND c.relkind = 'r' AND c.relrowsecurity
 GROUP BY c.relname, c.relrowsecurity
 ORDER BY c.relname;

\echo '\n### E3. Do any SECURITY DEFINER functions have an unpinned search_path?\n'
-- Zero rows is the passing answer. A row here is a privilege escalation finding.
SELECT p.proname AS unpinned_definer_function
  FROM pg_proc p
  JOIN pg_namespace n ON n.oid = p.pronamespace
 WHERE n.nspname = 'public'
   AND p.prosecdef
   AND (p.proconfig IS NULL OR NOT array_to_string(p.proconfig, ',') LIKE '%search_path%');

\echo '\n### E4. Can any role read a card token in plaintext?\n'
-- The schema stores only token_hash. A column literally named "token" would be
-- a finding; zero rows is the passing answer.
SELECT table_name, column_name, data_type
  FROM information_schema.columns
 WHERE table_schema = 'public'
   AND column_name IN ('token','plain_token','token_plaintext');

\echo '\n### E5. What exactly can the resolver read?\n'
-- Least privilege on the highest-traffic, least-trusted service. Expect three
-- columns of one table and nothing else.
SELECT table_name, column_name, privilege_type
  FROM information_schema.column_privileges
 WHERE grantee = 'app_resolver'
 ORDER BY table_name, column_name;

\echo '\n### E6. Which credentials are stored, and with which algorithm class?\n'
-- Documented in Step 3 §5. High-entropy secrets use SHA-256 because brute force
-- is infeasible; low-entropy human-entered secrets use Argon2id.
SELECT 'accounts.password_hash'  AS secret, 'Argon2id'  AS algorithm, 'human-chosen, low entropy'      AS rationale
UNION ALL SELECT 'cards.claim_code_hash',   'Argon2id',  'human-typed scratch code, ~60 bits'
UNION ALL SELECT 'cards.token_hash',        'SHA-256',   '128-bit CSPRNG, no pepper (see note)'
UNION ALL SELECT 'refresh_tokens.token_hash','SHA-256',  '256-bit CSPRNG, high entropy'
UNION ALL SELECT 'otp_codes.code_hash',     'Argon2id',  'six digits, rate-limited'
 ORDER BY 1;

\echo '\n### E7. Integrity constraint inventory (the ownership invariants)\n'
SELECT conname AS constraint_name,
       CASE contype WHEN 'f' THEN 'foreign key'
                    WHEN 'c' THEN 'check'
                    WHEN 'u' THEN 'unique'
                    WHEN 'p' THEN 'primary key' END AS kind,
       convalidated AS validated
  FROM pg_constraint
 WHERE conrelid = 'cards'::regclass
 ORDER BY contype, conname;

\echo '\n### E8. Is partition management current? (writes fail without a partition)\n'
SELECT parent.relname AS partitioned_table,
       count(child.relname) AS partition_count,
       max(child.relname)   AS newest_partition
  FROM pg_inherits i
  JOIN pg_class parent ON parent.oid = i.inhparent
  JOIN pg_class child  ON child.oid  = i.inhrelid
 WHERE parent.relname IN ('tap_events','audit_log','tap_events_eu','tap_events_us','tap_events_in')
 GROUP BY parent.relname
 ORDER BY parent.relname;

\echo '\n### E9. Which roles exist, and can any of them bypass RLS or log in?\n'
-- BYPASSRLS or SUPERUSER on an application role is a finding.
SELECT rolname, rolsuper AS superuser, rolbypassrls AS bypasses_rls, rolcanlogin AS can_login
  FROM pg_roles
 WHERE rolname LIKE 'app%'
 ORDER BY rolname;

\echo '\n### E10. Does any table holding visitor data carry a raw IP address?\n'
-- GDPR posture from §8: country is derived at ingest and the address discarded.
-- Zero rows is the passing answer.
SELECT table_name, column_name
  FROM information_schema.columns
 WHERE table_schema = 'public'
   AND (column_name LIKE '%ip_address%' OR data_type IN ('inet','cidr'));

\echo '\n### Evidence pack complete.\n'
`````

## `sql/98_auth_rls_tests.sql`

`````sql
-- ============================================================
-- Step 3 — RLS and refresh-token verification
--
-- Run AFTER 04_auth_hardening.sql, in its own psql session (the temp tables
-- must not collide with 99_constraint_tests.sql).
--
-- Every scenario runs as a real restricted role. Testing RLS as superuser is
-- meaningless -- superusers and table owners bypass policies entirely, which is
-- the classic way a team convinces itself RLS is working when it is not.
-- ============================================================

\set ON_ERROR_STOP on
SET client_min_messages TO WARNING;

CREATE TEMP TABLE rls_results (label text, expected text, got text);

-- Scoping predicates are applied DIRECTLY to base tables, never through a view.
-- A view owned by postgres reads its base tables with the VIEW OWNER's
-- privileges unless security_invoker=true, which silently bypasses RLS and
-- turns these assertions into false passes. Base tables only, deliberately.
GRANT ALL ON rls_results TO app_rw, app_renderer, app_resolver, app_auth;

CREATE OR REPLACE FUNCTION expect_reject_rls(label text, stmt text) RETURNS void AS $$
BEGIN
    BEGIN
        EXECUTE stmt;
        INSERT INTO rls_results VALUES (label, 'reject', 'FAIL — was accepted');
    EXCEPTION WHEN others THEN
        INSERT INTO rls_results VALUES (label, 'reject', 'reject');
    END;
END $$ LANGUAGE plpgsql;

-- ============================================================
-- Fixtures
-- ============================================================

INSERT INTO organizations (id, name, billing_email, data_region) VALUES
  ('00000000-0000-0000-0001-0000000000a1', 'Acme Two',  'b@acme2.test',  'eu'),
  ('00000000-0000-0000-0001-0000000000a2', 'Rival Two', 'b@rival2.test', 'us');

INSERT INTO accounts (id, email, full_name, data_region, status) VALUES
  ('00000000-0000-0000-0001-0000000000b1', 'alice@t.test', 'Alice', 'eu', 'active'),
  ('00000000-0000-0000-0001-0000000000b2', 'bob@t.test',   'Bob',   'eu', 'active');

-- Alice is an Acme Two employee. Bob is not in any organisation.
INSERT INTO org_memberships (org_id, account_id, role, status, joined_at) VALUES
  ('00000000-0000-0000-0001-0000000000a1','00000000-0000-0000-0001-0000000000b1','employee','active', now());

BEGIN;
INSERT INTO profiles (id, owner_account_id, current_slug, display_name, status) VALUES
  ('00000000-0000-0000-0001-0000000000c1', '00000000-0000-0000-0001-0000000000b1', 'alice', 'Alice', 'active');
INSERT INTO slugs (slug, kind, profile_id) VALUES ('alice','current','00000000-0000-0000-0001-0000000000c1');

INSERT INTO profiles (id, owner_account_id, current_slug, display_name, status) VALUES
  ('00000000-0000-0000-0001-0000000000c2', '00000000-0000-0000-0001-0000000000b2', 'bob', 'Bob', 'active');
INSERT INTO slugs (slug, kind, profile_id) VALUES ('bob','current','00000000-0000-0000-0001-0000000000c2');

INSERT INTO profiles (id, owner_org_id, current_slug, display_name, status) VALUES
  ('00000000-0000-0000-0001-0000000000c3', '00000000-0000-0000-0001-0000000000a1', 'acme2-desk', 'Acme Two Desk', 'active');
INSERT INTO slugs (slug, kind, profile_id) VALUES ('acme2-desk','current','00000000-0000-0000-0001-0000000000c3');

INSERT INTO profiles (id, owner_org_id, current_slug, display_name, status) VALUES
  ('00000000-0000-0000-0001-0000000000c4', '00000000-0000-0000-0001-0000000000a1', 'acme2-draft', 'Acme Two Draft', 'draft');
INSERT INTO slugs (slug, kind, profile_id) VALUES ('acme2-draft','current','00000000-0000-0000-0001-0000000000c4');
COMMIT;

INSERT INTO cards (id, token_hash, token_prefix, chip, owner_account_id,
                   holder_account_id, profile_id, serving_slug, serving_state, status, locked_at)
VALUES ('00000000-0000-0000-0001-0000000000d1', '\xa1'::bytea, 'zzzzzz', 'ntag213',
        '00000000-0000-0000-0001-0000000000b1',
        '00000000-0000-0000-0001-0000000000b1',
        '00000000-0000-0000-0001-0000000000c1', 'alice', 'active', 'active', now());

INSERT INTO sessions (id, account_id, device_label, expires_at) VALUES
  ('00000000-0000-0000-0001-0000000000e1','00000000-0000-0000-0001-0000000000b1','Alice iPhone', now() + interval '12 hours'),
  ('00000000-0000-0000-0001-0000000000e2','00000000-0000-0000-0001-0000000000b2','Bob Pixel',    now() + interval '12 hours');

-- ============================================================
-- 1. RLS fails CLOSED when no identity is set
-- ============================================================

BEGIN;
SET ROLE app_rw;
INSERT INTO rls_results
  VALUES ('no identity set -> zero profiles', '0', (SELECT count(*)::text FROM profiles WHERE current_slug IN ('alice','bob','acme2-desk','acme2-draft')));
INSERT INTO rls_results
  VALUES ('no identity set -> zero cards', '0', (SELECT count(*)::text FROM cards WHERE token_prefix = 'zzzzzz'));
RESET ROLE;
COMMIT;

-- ============================================================
-- 2. Tenant isolation
-- ============================================================

BEGIN;
SET ROLE app_rw;
SET LOCAL app.account_id = '00000000-0000-0000-0001-0000000000b1';
-- Alice: her own profile + both Acme Two profiles (she is an active member).
INSERT INTO rls_results
  VALUES ('alice sees own + org profiles', '3', (SELECT count(*)::text FROM profiles WHERE current_slug IN ('alice','bob','acme2-desk','acme2-draft')));
INSERT INTO rls_results
  VALUES ('alice cannot see bob''s profile', '0',
          (SELECT count(*)::text FROM profiles WHERE current_slug = 'bob'));
INSERT INTO rls_results
  VALUES ('alice sees her own card', '1', (SELECT count(*)::text FROM cards WHERE token_prefix = 'zzzzzz'));
INSERT INTO rls_results
  VALUES ('alice sees only her own session', '1', (SELECT count(*)::text FROM sessions WHERE device_label IN ('Alice iPhone','Bob Pixel')));
RESET ROLE;
COMMIT;

BEGIN;
SET ROLE app_rw;
SET LOCAL app.account_id = '00000000-0000-0000-0001-0000000000b2';
-- Bob is in no organisation, so he sees exactly one profile.
INSERT INTO rls_results
  VALUES ('bob sees only his own profile', '1', (SELECT count(*)::text FROM profiles WHERE current_slug IN ('alice','bob','acme2-desk','acme2-draft')));
INSERT INTO rls_results
  VALUES ('bob sees no cards', '0', (SELECT count(*)::text FROM cards WHERE token_prefix = 'zzzzzz'));
INSERT INTO rls_results
  VALUES ('bob cannot see alice''s session', '0',
          (SELECT count(*)::text FROM sessions WHERE device_label = 'Alice iPhone'));
RESET ROLE;
COMMIT;

-- ============================================================
-- 3. WITH CHECK blocks writing into another tenant
-- ============================================================

BEGIN;
SET ROLE app_rw;
SET LOCAL app.account_id = '00000000-0000-0000-0001-0000000000b1';
SELECT expect_reject_rls('alice cannot create a profile owned by bob', $$
  INSERT INTO profiles (owner_account_id, current_slug, display_name)
  VALUES ('00000000-0000-0000-0001-0000000000b2', 'alice-forged', 'Forged')
$$);
SELECT expect_reject_rls('alice cannot reassign her profile to bob', $$
  UPDATE profiles SET owner_account_id = '00000000-0000-0000-0001-0000000000b2'
   WHERE current_slug = 'alice'
$$);
SELECT expect_reject_rls('alice cannot create a profile for an org she is not in', $$
  INSERT INTO profiles (owner_org_id, current_slug, display_name)
  VALUES ('00000000-0000-0000-0001-0000000000a2', 'rival-forged', 'Forged')
$$);
RESET ROLE;
ROLLBACK;

-- ============================================================
-- 4. Service roles see exactly what they need
-- ============================================================

BEGIN;
SET ROLE app_renderer;
-- The renderer must never serve a draft, and that is a policy, not a filter it
-- is trusted to remember. 4 profiles exist; 3 are active.
INSERT INTO rls_results
  VALUES ('renderer sees active profiles only', '3', (SELECT count(*)::text FROM profiles WHERE current_slug IN ('alice','bob','acme2-desk','acme2-draft')));
RESET ROLE;
COMMIT;

BEGIN;
SET ROLE app_resolver;
-- Resolves any token: it has no user context. Counting a granted column,
-- because column-level privileges do not permit count(*).
INSERT INTO rls_results
  VALUES ('resolver can resolve any card', '1', (SELECT count(token_hash)::text FROM cards WHERE token_hash = '\xa1'::bytea));
RESET ROLE;
COMMIT;

BEGIN;
SET ROLE app_resolver;
SELECT expect_reject_rls('resolver cannot read profile content', $$
  SELECT bio FROM profiles LIMIT 1
$$);
SELECT expect_reject_rls('resolver cannot read accounts', $$
  SELECT email FROM accounts LIMIT 1
$$);
SELECT expect_reject_rls('resolver cannot read a card''s claim code hash', $$
  SELECT claim_code_hash FROM cards LIMIT 1
$$);
RESET ROLE;
ROLLBACK;

-- ============================================================
-- 5. Refresh token rotation and reuse detection
-- ============================================================

-- Issue the first token for Alice's session.
INSERT INTO refresh_tokens (id, session_id, token_hash, expires_at) VALUES
  ('00000000-0000-0000-0001-0000000000f1','00000000-0000-0000-0001-0000000000e1',
   '\xb1'::bytea, now() + interval '30 days');

SELECT expect_reject_rls('a used token with no successor', $$
  UPDATE refresh_tokens SET used_at = now()
   WHERE id = '00000000-0000-0000-0001-0000000000f1'
$$);

SELECT expect_reject_rls('a token that expires before it was issued', $$
  INSERT INTO refresh_tokens (session_id, token_hash, issued_at, expires_at)
  VALUES ('00000000-0000-0000-0001-0000000000e1', '\xbf'::bytea,
          now(), now() - interval '1 hour')
$$);

SELECT expect_reject_rls('two tokens sharing a hash', $$
  INSERT INTO refresh_tokens (session_id, token_hash, expires_at)
  VALUES ('00000000-0000-0000-0001-0000000000e1', '\xb1'::bytea, now() + interval '30 days')
$$);

-- Rotation: issue the successor, then mark the predecessor used, atomically.
BEGIN;
INSERT INTO refresh_tokens (id, session_id, token_hash, expires_at) VALUES
  ('00000000-0000-0000-0001-0000000000f2','00000000-0000-0000-0001-0000000000e1',
   '\xb2'::bytea, now() + interval '30 days');
UPDATE refresh_tokens
   SET used_at = now(), replaced_by = '00000000-0000-0000-0001-0000000000f2'
 WHERE id = '00000000-0000-0000-0001-0000000000f1';
COMMIT;

INSERT INTO rls_results
  VALUES ('rotation marks the predecessor used', 'used',
          (SELECT CASE WHEN used_at IS NOT NULL AND replaced_by IS NOT NULL
                       THEN 'used' ELSE 'not-used' END
             FROM refresh_tokens WHERE id = '00000000-0000-0000-0001-0000000000f1'));

-- The replay: a client presenting \xb1 again. A used row is found, which is
-- proof of theft, because a correct client discards a token on exchange.
INSERT INTO rls_results
  VALUES ('replayed token is detectable as used', 'replay-detected',
          (SELECT CASE WHEN used_at IS NOT NULL THEN 'replay-detected' ELSE 'undetected' END
             FROM refresh_tokens WHERE token_hash = '\xb1'::bytea));

-- Response to detection: revoke the whole session, which cascades the family.
UPDATE sessions SET revoked_at = now(), revoked_reason = 'refresh_reuse_detected'
 WHERE id = '00000000-0000-0000-0001-0000000000e1';

INSERT INTO rls_results
  VALUES ('reuse revokes the entire session', 'refresh_reuse_detected',
          (SELECT revoked_reason FROM sessions WHERE id = '00000000-0000-0000-0001-0000000000e1'));

INSERT INTO rls_results
  VALUES ('both family tokens still auditable after revocation', '2',
          (SELECT count(*)::text FROM refresh_tokens
            WHERE session_id = '00000000-0000-0000-0001-0000000000e1'));

-- ============================================================
-- 6. SECURITY DEFINER hygiene
-- ============================================================

INSERT INTO rls_results
  VALUES ('definer function has a pinned search_path', 'pinned',
          (SELECT CASE WHEN array_to_string(proconfig, ',') LIKE '%search_path%'
                       THEN 'pinned' ELSE 'UNPINNED — escalation risk' END
             FROM pg_proc WHERE proname = 'app_current_org_ids'));

INSERT INTO rls_results
  VALUES ('definer function is not executable by PUBLIC', 'restricted',
          (SELECT CASE WHEN has_function_privilege('public', 'app_current_org_ids()', 'EXECUTE')
                       THEN 'PUBLIC CAN EXECUTE' ELSE 'restricted' END));

-- ============================================================
-- Report
-- ============================================================

\echo ''
\echo '=== RLS and refresh-token verification ==='
SELECT label, expected, got FROM rls_results WHERE got IS DISTINCT FROM expected;
SELECT count(*) FILTER (WHERE got = expected)                AS passed,
       count(*) FILTER (WHERE got IS DISTINCT FROM expected) AS failed
  FROM rls_results;
`````

## `sql/99_constraint_tests.sql`

`````sql
-- ============================================================
-- Step 2 — constraint verification
--
-- Every invariant claimed in the architecture is asserted here against a real
-- Postgres. A design document that says "the database enforces this" is a
-- promise; this file is the evidence.
-- ============================================================

\set ON_ERROR_STOP on
SET client_min_messages TO WARNING;

CREATE TEMP TABLE results (label text, expectation text, outcome text);
-- The append-only tests run AS app_rw, so that role must be able to record its
-- own results. The helpers are deliberately NOT security definer: the statement
-- under test has to execute with the restricted role's real privileges.
GRANT ALL ON results TO app_rw;

-- Asserts a statement is REJECTED. Records a failure if it succeeds.
CREATE OR REPLACE FUNCTION expect_reject(label text, stmt text) RETURNS void AS $$
BEGIN
    BEGIN
        EXECUTE stmt;
        INSERT INTO results VALUES (label, 'reject', 'FAIL — was accepted');
    EXCEPTION WHEN others THEN
        INSERT INTO results VALUES (label, 'reject', 'ok');
    END;
END $$ LANGUAGE plpgsql;

-- Asserts a statement is ACCEPTED.
CREATE OR REPLACE FUNCTION expect_accept(label text, stmt text) RETURNS void AS $$
BEGIN
    BEGIN
        EXECUTE stmt;
        INSERT INTO results VALUES (label, 'accept', 'ok');
    EXCEPTION WHEN others THEN
        INSERT INTO results VALUES (label, 'accept', 'FAIL — ' || SQLERRM);
    END;
END $$ LANGUAGE plpgsql;

-- ============================================================
-- Fixtures: two people, two organisations
-- ============================================================

INSERT INTO organizations (id, name, billing_email, data_region) VALUES
  ('00000000-0000-0000-0000-0000000000a1', 'Acme Ltd',  'billing@acme.test', 'eu'),
  ('00000000-0000-0000-0000-0000000000a2', 'Rival Inc', 'billing@rival.test','us');

INSERT INTO accounts (id, email, full_name, data_region, status) VALUES
  ('00000000-0000-0000-0000-0000000000b1', 'vaibhav@example.test', 'Vaibhav', 'eu', 'active'),
  ('00000000-0000-0000-0000-0000000000b2', 'mallory@example.test', 'Mallory', 'eu', 'active'),
  ('00000000-0000-0000-0000-0000000000b3', 'encoder@acme.test',    'Encoder', 'eu', 'active');

-- Vaibhav is an Acme employee. Mallory is not.
INSERT INTO org_memberships (org_id, account_id, role, status, joined_at) VALUES
  ('00000000-0000-0000-0000-0000000000a1','00000000-0000-0000-0000-0000000000b1','employee','active', now());

-- Personal profile (Vaibhav's), Mallory's, an Acme work profile, a Rival work profile.
-- NOTE: profiles.current_slug -> slugs.slug is DEFERRABLE INITIALLY DEFERRED, so a
-- profile and its first slug MUST be created inside one transaction. This is a real
-- constraint on the write path, not a test artifact — the repository layer has to
-- honour it.

BEGIN;
INSERT INTO profiles (id, owner_account_id, current_slug, display_name, status) VALUES
  ('00000000-0000-0000-0000-0000000000c1','00000000-0000-0000-0000-0000000000b1','vaibhav','Vaibhav','active');
INSERT INTO slugs (slug, kind, profile_id) VALUES ('vaibhav','current','00000000-0000-0000-0000-0000000000c1');

INSERT INTO profiles (id, owner_account_id, current_slug, display_name, status) VALUES
  ('00000000-0000-0000-0000-0000000000c2','00000000-0000-0000-0000-0000000000b2','mallory','Mallory','active');
INSERT INTO slugs (slug, kind, profile_id) VALUES ('mallory','current','00000000-0000-0000-0000-0000000000c2');

INSERT INTO profiles (id, owner_org_id, current_slug, display_name, status) VALUES
  ('00000000-0000-0000-0000-0000000000c3','00000000-0000-0000-0000-0000000000a1','acme-vaibhav','Vaibhav at Acme','active');
INSERT INTO slugs (slug, kind, profile_id) VALUES ('acme-vaibhav','current','00000000-0000-0000-0000-0000000000c3');

INSERT INTO profiles (id, owner_org_id, current_slug, display_name, status) VALUES
  ('00000000-0000-0000-0000-0000000000c4','00000000-0000-0000-0000-0000000000a2','rival-desk','Rival Desk','active');
INSERT INTO slugs (slug, kind, profile_id) VALUES ('rival-desk','current','00000000-0000-0000-0000-0000000000c4');
COMMIT;

-- ============================================================
-- 1. Ownership invariants (MATCH SIMPLE composite foreign keys)
-- ============================================================

SELECT expect_accept('personal card -> own profile', $$
  INSERT INTO cards (id, token_hash, token_prefix, chip, owner_account_id,
                     holder_account_id, profile_id, serving_slug, serving_state,
                     status, locked_at)
  VALUES ('00000000-0000-0000-0000-0000000000d1', '\x01'::bytea, 'aaaaaa', 'ntag213',
          '00000000-0000-0000-0000-0000000000b1',
          '00000000-0000-0000-0000-0000000000b1',
          '00000000-0000-0000-0000-0000000000c1', 'vaibhav', 'active', 'active', now())
$$);

SELECT expect_reject('personal card -> someone else''s profile', $$
  INSERT INTO cards (token_hash, token_prefix, chip, owner_account_id,
                     holder_account_id, profile_id, serving_slug, status, locked_at)
  VALUES ('\x02'::bytea, 'bbbbbb', 'ntag213',
          '00000000-0000-0000-0000-0000000000b1',
          '00000000-0000-0000-0000-0000000000b1',
          '00000000-0000-0000-0000-0000000000c2', 'mallory', 'active', now())
$$);

SELECT expect_accept('org card -> org profile, holder is member', $$
  INSERT INTO cards (id, token_hash, token_prefix, chip, dna_key_ref, owner_org_id,
                     holder_account_id, profile_id, serving_slug, serving_state,
                     status, locked_at)
  VALUES ('00000000-0000-0000-0000-0000000000d2', '\x03'::bytea, 'cccccc', 'ntag424_dna',
          'kms://nfc-dna/master/v1#card-d2',
          '00000000-0000-0000-0000-0000000000a1',
          '00000000-0000-0000-0000-0000000000b1',
          '00000000-0000-0000-0000-0000000000c3', 'acme-vaibhav', 'active', 'active', now())
$$);

-- THE decision from §2.6, enforced in the database rather than in a code review.
SELECT expect_reject('org card -> personal profile', $$
  INSERT INTO cards (token_hash, token_prefix, chip, owner_org_id,
                     holder_account_id, profile_id, serving_slug, status, locked_at)
  VALUES ('\x04'::bytea, 'dddddd', 'ntag213',
          '00000000-0000-0000-0000-0000000000a1',
          '00000000-0000-0000-0000-0000000000b1',
          '00000000-0000-0000-0000-0000000000c1', 'vaibhav', 'active', now())
$$);

SELECT expect_reject('org card -> another org''s profile', $$
  INSERT INTO cards (token_hash, token_prefix, chip, owner_org_id,
                     holder_account_id, profile_id, serving_slug, status, locked_at)
  VALUES ('\x05'::bytea, 'eeeeee', 'ntag213',
          '00000000-0000-0000-0000-0000000000a1',
          '00000000-0000-0000-0000-0000000000b1',
          '00000000-0000-0000-0000-0000000000c4', 'rival-desk', 'active', now())
$$);

SELECT expect_reject('org card -> holder is not a member', $$
  INSERT INTO cards (token_hash, token_prefix, chip, owner_org_id,
                     holder_account_id, profile_id, serving_slug, status, locked_at)
  VALUES ('\x06'::bytea, 'ffffff', 'ntag213',
          '00000000-0000-0000-0000-0000000000a1',
          '00000000-0000-0000-0000-0000000000b2',
          '00000000-0000-0000-0000-0000000000c3', 'acme-vaibhav', 'active', now())
$$);

SELECT expect_reject('card with two owners', $$
  INSERT INTO cards (token_hash, token_prefix, chip, owner_org_id, owner_account_id,
                     holder_account_id, profile_id, status)
  VALUES ('\x07'::bytea, 'gggggg', 'ntag213',
          '00000000-0000-0000-0000-0000000000a1',
          '00000000-0000-0000-0000-0000000000b1',
          '00000000-0000-0000-0000-0000000000b1',
          '00000000-0000-0000-0000-0000000000c3', 'provisioned')
$$);

-- ============================================================
-- 2. Card state integrity
-- ============================================================

SELECT expect_reject('active card that was never locked', $$
  INSERT INTO cards (token_hash, token_prefix, chip, owner_account_id,
                     holder_account_id, profile_id, serving_slug, status)
  VALUES ('\x08'::bytea, 'hhhhhh', 'ntag213',
          '00000000-0000-0000-0000-0000000000b1',
          '00000000-0000-0000-0000-0000000000b1',
          '00000000-0000-0000-0000-0000000000c1', 'vaibhav', 'active')
$$);

SELECT expect_reject('active card with no profile bound', $$
  INSERT INTO cards (token_hash, token_prefix, chip, owner_account_id,
                     holder_account_id, status, locked_at)
  VALUES ('\x09'::bytea, 'iiiiii', 'ntag213',
          '00000000-0000-0000-0000-0000000000b1',
          '00000000-0000-0000-0000-0000000000b1', 'active', now())
$$);

SELECT expect_reject('revoked card with no reason', $$
  INSERT INTO cards (token_hash, token_prefix, chip, status, serving_state, revoked_at)
  VALUES ('\x0a'::bytea, 'jjjjjj', 'ntag213', 'revoked', 'revoked', now())
$$);

SELECT expect_reject('DNA chip with no key reference', $$
  INSERT INTO cards (token_hash, token_prefix, chip, status)
  VALUES ('\x0b'::bytea, 'kkkkkk', 'ntag424_dna', 'manufactured')
$$);

SELECT expect_reject('basic chip claiming a DNA key', $$
  INSERT INTO cards (token_hash, token_prefix, chip, status, dna_key_ref)
  VALUES ('\x0c'::bytea, 'llllll', 'ntag213', 'manufactured', 'kms://key/1')
$$);

SELECT expect_reject('duplicate token hash', $$
  INSERT INTO cards (token_hash, token_prefix, chip, status)
  VALUES ('\x01'::bytea, 'mmmmmm', 'ntag213', 'manufactured')
$$);

-- ============================================================
-- 3. Permanent identity — the slug namespace
-- ============================================================

SELECT expect_reject('reusing a slug for a different profile', $$
  INSERT INTO slugs (slug, kind, profile_id)
  VALUES ('vaibhav', 'current', '00000000-0000-0000-0000-0000000000c2')
$$);

SELECT expect_reject('claiming a reserved slug', $$
  INSERT INTO slugs (slug, kind, profile_id)
  VALUES ('admin', 'current', '00000000-0000-0000-0000-0000000000c2')
$$);

SELECT expect_reject('two current slugs for one profile', $$
  INSERT INTO slugs (slug, kind, profile_id)
  VALUES ('vaibhav-two', 'current', '00000000-0000-0000-0000-0000000000c1')
$$);

SELECT expect_reject('slug with invalid characters', $$
  INSERT INTO slugs (slug, kind, profile_id)
  VALUES ('Bad_Slug!', 'current', '00000000-0000-0000-0000-0000000000c2')
$$);

SELECT expect_reject('retired slug with no retirement timestamp', $$
  INSERT INTO slugs (slug, kind, profile_id)
  VALUES ('old-handle', 'retired', '00000000-0000-0000-0000-0000000000c1')
$$);

-- A rename keeps the old slug alive forever, pointing at the same profile.
SELECT expect_accept('rename retires the old slug and keeps it', $$
  UPDATE slugs SET kind = 'retired', retired_at = now() WHERE slug = 'vaibhav';
  INSERT INTO slugs (slug, kind, profile_id)
    VALUES ('vaibhav-k', 'current', '00000000-0000-0000-0000-0000000000c1');
  UPDATE profiles SET current_slug = 'vaibhav-k'
    WHERE id = '00000000-0000-0000-0000-0000000000c1';
  UPDATE cards SET serving_slug = 'vaibhav-k'
    WHERE profile_id = '00000000-0000-0000-0000-0000000000c1'
$$);

SELECT expect_reject('a third party grabbing the retired slug', $$
  INSERT INTO slugs (slug, kind, profile_id)
  VALUES ('vaibhav', 'current', '00000000-0000-0000-0000-0000000000c2')
$$);

-- ============================================================
-- 4. Encoding and locking
-- ============================================================

SELECT expect_reject('locked chip whose verify read failed', $$
  INSERT INTO card_encodings (card_id, encoder_account_id, station_id, chip, locked, verify_read_ok)
  VALUES ('00000000-0000-0000-0000-0000000000d1',
          '00000000-0000-0000-0000-0000000000b3', 'station-01', 'ntag213', true, false)
$$);

SELECT expect_accept('locked chip with a successful verify read', $$
  INSERT INTO card_encodings (card_id, encoder_account_id, station_id, chip, locked, verify_read_ok)
  VALUES ('00000000-0000-0000-0000-0000000000d1',
          '00000000-0000-0000-0000-0000000000b3', 'station-01', 'ntag213', true, true)
$$);

-- ============================================================
-- 5. Transfers
-- ============================================================

SELECT expect_accept('activation transfer has no origin', $$
  INSERT INTO ownership_transfers (card_id, to_account_id, reason)
  VALUES ('00000000-0000-0000-0000-0000000000d1',
          '00000000-0000-0000-0000-0000000000b1', 'activation')
$$);

SELECT expect_reject('activation transfer with an origin', $$
  INSERT INTO ownership_transfers (card_id, from_account_id, to_account_id, reason)
  VALUES ('00000000-0000-0000-0000-0000000000d1',
          '00000000-0000-0000-0000-0000000000b2',
          '00000000-0000-0000-0000-0000000000b1', 'activation')
$$);

SELECT expect_reject('sale transfer with no origin', $$
  INSERT INTO ownership_transfers (card_id, to_account_id, reason, approved_by)
  VALUES ('00000000-0000-0000-0000-0000000000d1',
          '00000000-0000-0000-0000-0000000000b2', 'sale',
          '00000000-0000-0000-0000-0000000000b3')
$$);

SELECT expect_reject('transfer to two destinations at once', $$
  INSERT INTO ownership_transfers (card_id, from_account_id, to_account_id, to_org_id, reason, approved_by)
  VALUES ('00000000-0000-0000-0000-0000000000d1',
          '00000000-0000-0000-0000-0000000000b1',
          '00000000-0000-0000-0000-0000000000b2',
          '00000000-0000-0000-0000-0000000000a1', 'sale',
          '00000000-0000-0000-0000-0000000000b3')
$$);

SELECT expect_reject('non-activation transfer with no approver', $$
  INSERT INTO ownership_transfers (card_id, from_account_id, to_account_id, reason)
  VALUES ('00000000-0000-0000-0000-0000000000d1',
          '00000000-0000-0000-0000-0000000000b1',
          '00000000-0000-0000-0000-0000000000b2', 'sale')
$$);

-- ============================================================
-- 6. Subscriptions
-- ============================================================

SELECT expect_accept('personal subscription, one seat', $$
  INSERT INTO subscriptions (owner_account_id, plan, status, seats)
  VALUES ('00000000-0000-0000-0000-0000000000b1', 'pro', 'active', 1)
$$);

SELECT expect_reject('personal subscription with multiple seats', $$
  INSERT INTO subscriptions (owner_account_id, plan, status, seats)
  VALUES ('00000000-0000-0000-0000-0000000000b2', 'pro', 'active', 5)
$$);

SELECT expect_reject('second live subscription for one account', $$
  INSERT INTO subscriptions (owner_account_id, plan, status, seats)
  VALUES ('00000000-0000-0000-0000-0000000000b1', 'pro', 'active', 1)
$$);

SELECT expect_reject('subscription owned by both an account and an org', $$
  INSERT INTO subscriptions (owner_account_id, owner_org_id, plan, status)
  VALUES ('00000000-0000-0000-0000-0000000000b2',
          '00000000-0000-0000-0000-0000000000a1', 'team', 'active')
$$);

SELECT expect_accept('org subscription with many seats', $$
  INSERT INTO subscriptions (owner_org_id, plan, status, seats)
  VALUES ('00000000-0000-0000-0000-0000000000a1', 'team', 'active', 50)
$$);

-- ============================================================
-- 7. Erasure vs immutable audit (§10)
-- ============================================================

SELECT expect_accept('audit row referencing an actor by opaque id', $$
  INSERT INTO audit_log (actor_scope, actor_account_id, action, subject_type, subject_id)
  VALUES ('account', '00000000-0000-0000-0000-0000000000b2', 'profile.update',
          'profile', '00000000-0000-0000-0000-0000000000c2')
$$);

SELECT expect_reject('a non-system action with no actor', $$
  INSERT INTO audit_log (actor_scope, action, subject_type)
  VALUES ('account', 'profile.update', 'profile')
$$);

SELECT expect_accept('system action with no actor', $$
  INSERT INTO audit_log (actor_scope, action, subject_type)
  VALUES ('system', 'serving_state.reconcile', 'card')
$$);

SELECT expect_reject('tombstoning while personal data remains', $$
  UPDATE accounts SET tombstoned_at = now(), status = 'tombstoned'
  WHERE id = '00000000-0000-0000-0000-0000000000b2'
$$);

SELECT expect_accept('tombstoning that actually erases the person', $$
  UPDATE accounts
     SET tombstoned_at = now(), status = 'tombstoned',
         email = NULL, password_hash = NULL, full_name = NULL
   WHERE id = '00000000-0000-0000-0000-0000000000b2'
$$);

-- The audit trail survives the erasure it describes.
SELECT expect_accept('audit row survives actor erasure', $$
  DO $inner$
  BEGIN
    IF NOT EXISTS (
      SELECT 1 FROM audit_log
       WHERE actor_account_id = '00000000-0000-0000-0000-0000000000b2'
    ) THEN RAISE EXCEPTION 'audit row vanished with the account';
    END IF;
  END $inner$
$$);

SELECT expect_accept('tombstoning frees the email address for reuse', $$
  INSERT INTO accounts (email, full_name, data_region, status)
  VALUES ('mallory@example.test', 'Someone Else', 'eu', 'active')
$$);

-- ============================================================
-- 8. Analytics partition routing
-- ============================================================

SELECT expect_accept('tap event routes to its region and month', $$
  INSERT INTO tap_events (occurred_at, region, card_id, profile_id, channel, country, device_class)
  VALUES ('2026-08-15 10:00+00', 'eu', '00000000-0000-0000-0000-0000000000d1',
          '00000000-0000-0000-0000-0000000000c1', 'nfc', 'DE', 'android-phone')
$$);

SELECT expect_accept('a QR scan is the same event with a different channel', $$
  INSERT INTO tap_events (occurred_at, region, profile_id, channel, country)
  VALUES ('2026-09-02 11:00+00', 'in', '00000000-0000-0000-0000-0000000000c1', 'qr', 'IN')
$$);

SELECT expect_reject('event in a region with no partition', $$
  INSERT INTO tap_events (occurred_at, region, profile_id, channel)
  VALUES ('2026-08-15 10:00+00', 'us', '00000000-0000-0000-0000-0000000000c1', 'nfc');
  INSERT INTO tap_events (occurred_at, region, profile_id, channel)
  VALUES ('2030-01-01 10:00+00', 'us', '00000000-0000-0000-0000-0000000000c1', 'nfc')
$$);

-- ============================================================
-- 9. Append-only enforced by GRANT, not by convention (§10)
-- ============================================================

SET ROLE app_rw;

SELECT expect_reject('app role rewriting ownership history', $$
  UPDATE ownership_transfers SET reason = 'gift'
$$);

SELECT expect_reject('app role deleting ownership history', $$
  DELETE FROM ownership_transfers
$$);

SELECT expect_reject('app role editing the audit log', $$
  UPDATE audit_log SET action = 'nothing.happened'
$$);

SELECT expect_reject('app role deleting audit rows', $$
  DELETE FROM audit_log
$$);

SELECT expect_reject('app role rewriting an encoding record', $$
  UPDATE card_encodings SET locked = false
$$);

SELECT expect_reject('app role hard-deleting an account', $$
  DELETE FROM accounts
$$);

SELECT expect_reject('app role deleting a slug to free it', $$
  DELETE FROM slugs WHERE slug = 'vaibhav'
$$);

RESET ROLE;

-- ============================================================
-- Report
-- ============================================================

\echo ''
\echo '=== constraint verification ==='
SELECT label, expectation, outcome FROM results WHERE outcome <> 'ok';
SELECT count(*) FILTER (WHERE outcome = 'ok')  AS passed,
       count(*) FILTER (WHERE outcome <> 'ok') AS failed
  FROM results;
`````

## `sql/run.sh`

`````bash
#!/usr/bin/env bash
# Applies the schema to a scratch database, runs both verification suites, and
# prints the audit evidence pack.
#
#   ./run.sh                        # uses $PGDATABASE or 'nfc'
#   PGHOST=... PGPORT=... ./run.sh
set -euo pipefail
DB="${PGDATABASE:-nfc}"
DIR="$(cd "$(dirname "$0")" && pwd)"

psql -q -d postgres -c "DROP DATABASE IF EXISTS ${DB};" -c "CREATE DATABASE ${DB};"

for f in 01_core.sql 02_cards.sql 03_billing_audit_analytics.sql 04_auth_hardening.sql; do
  echo "applying ${f}"
  psql -q -d "${DB}" -v ON_ERROR_STOP=1 -f "${DIR}/${f}"
done

# The two suites are order-independent by design; each scopes its assertions to
# its own fixtures.
echo; echo "verifying constraints (Step 2)"
psql -q -d "${DB}" -f "${DIR}/99_constraint_tests.sql"

echo; echo "verifying RLS and refresh tokens (Step 3)"
psql -q -d "${DB}" -f "${DIR}/98_auth_rls_tests.sql"

echo; echo "audit evidence pack"
psql -q -d "${DB}" -f "${DIR}/97_audit_evidence.sql"
`````
